server:
  servlet:
    context-path:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

#redis
redis:
  host: 127.0.0.1
  password:
  port: 6379
  timeout: 3000
  jedis:
    pool:
      max-idle: 500
      min-idle: 50
      max-active: 2000
      max-wait: 1000
  testOnBorrow: true